name: Pull Request Template
description: Create a pull request for this project.
title: "[PR]: "
labels: []
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to contribute to our project!
    - type: markdown
      attributes:
          value: |
              Please fill out the following details to help us review your changes.
    - type: textarea
      id: summary
      attributes:
          label: Summary of Changes
          description: A clear and concise description of the changes made in this pull request.
      validations:
          required: true
    - type: textarea
      id: related-issues
      attributes:
          label: Related Issue(s)
          description: Reference any related issues (e.g., "Fixes #123").
      validations:
          required: false
    - type: textarea
      id: testing
      attributes:
          label: Testing Instructions
          description: Describe the steps you took to test your changes. Include any commands or instructions needed to reproduce the results.
      validations:
          required: true
    - type: textarea
      id: additional-info
      attributes:
          label: Additional Information
          description: Add any extra context or screenshots about the pull request here.
      validations:
          required: false
