name: Frontend Lint Check

on:
  pull_request:
    branches: [ main, master ]  # Runs on PRs to these branches
  push:
    branches: [ main, master ]  # Runs on direct pushes too

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use your project's Node.js version
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        working-directory: frontend
        run: pnpm install

      - name: Run ESLint
        working-directory: frontend
        run: pnpm run lint
