name: Type Check

on: [ push, pull_request ]

jobs:
  #  format:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - name: Set up Python
  #        uses: actions/setup-python@v3
  #        with:
  #          python-version: "3.8"
  #
  #      - name: Install dependencies
  #        run: |
  #          pip install black mypy
  #
  ##      - name: Check code format with Black
  ##        run: |
  ##          black --check .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install mypy

      - name: Run mypy for type checking
        run: |
          mypy sards
